# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Don < Formula
  desc ""
  homepage "https://git.xsfx.dev/xsteadfastx/don"
  version "1.2.0"
  bottle :unneeded
  depends_on :linux

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/xsteadfastx/don/releases/download/v1.2.0/don_1.2.0_linux_amd64.tar.gz"
      sha256 "3249956bde93d7c42af8fa62d86fb81736c4abc96fdb32d15090d1bdb3ed176b"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/xsteadfastx/don/releases/download/v1.2.0/don_1.2.0_linux_armv6.tar.gz"
      sha256 "3924069ea474c764ab88782ce5c69faceee8b782ad360300bc9be9f486b2ce70"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xsteadfastx/don/releases/download/v1.2.0/don_1.2.0_linux_arm64.tar.gz"
      sha256 "1449f5a0e4a66fb4d087c59dbc60b1fc9f4d555ab08465d2be49f1d43ec43f01"
    end
  end

  def install
    bin.install "don"
  end

  test do
    system "#{bin}/don version"
  end
end
