# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Don < Formula
  desc ""
  homepage "https://git.xsfx.dev/xsteadfastx/don"
  version "1.1.3"
  bottle :unneeded
  depends_on :linux

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/xsteadfastx/don/releases/download/v1.1.3/don_1.1.3_linux_amd64.tar.gz"
      sha256 "7d4db00e19db5306d3784225708404162c08c1c0f02a625e24f9316913ac1c2e"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/xsteadfastx/don/releases/download/v1.1.3/don_1.1.3_linux_armv6.tar.gz"
      sha256 "4ed4dd59f4ba5a077b0e1736aa513fdb902f2ab9835d1fae3f8113899e8bc4d6"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xsteadfastx/don/releases/download/v1.1.3/don_1.1.3_linux_arm64.tar.gz"
      sha256 "c447422c7de2fc1ef44009d85e3dfa1b889390b8c36f580bd8a174ac872a0f83"
    end
  end

  def install
    bin.install "don"
  end

  test do
    system "#{bin}/don version"
  end
end
