# This file was generated by GoReleaser. DO NOT EDIT.
class Fortlit < Formula
  desc ""
  homepage "https://git.xsfx.dev/xsteadfastx/fortlit"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/xsteadfastx/fortlit-go/releases/download/v0.2.0/fortlit_0.2.0_macos_amd64.tar.gz"
    sha256 "d6ffe550d6752be753ace92132f0040c887c791c9011ebf5aa5d25d5f9508864"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/xsteadfastx/fortlit-go/releases/download/v0.2.0/fortlit_0.2.0_linux_amd64.tar.gz"
    sha256 "ee91a7d8371927a302bf1eff0088d5ec6e684da7d3023a83700626e321c34cda"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/xsteadfastx/fortlit-go/releases/download/v0.2.0/fortlit_0.2.0_linux_armv6.tar.gz"
    sha256 "78ac4dd53c4d05be0c530a0d0be8e5817be39f0e1861eab4debcebca1e7ee853"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/xsteadfastx/fortlit-go/releases/download/v0.2.0/fortlit_0.2.0_linux_arm64.tar.gz"
    sha256 "eb706cd5a3b025e5ff057aa35a92519b9643246fb27594932008b61433f2b4be"
  end

  def install
    bin.install "fortlit"
  end

  test do
    system "#{bin}/fortlit -version"
  end
end
