# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WgQuicker < Formula
  desc ""
  homepage "https://git.xsfx.dev/xsteadfastx/wg-quicker"
  version "0.5.2"
  bottle :unneeded
  depends_on :linux

  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/xsteadfastx/wg-quicker/releases/download/v0.5.2/wg-quicker_0.5.2_linux_amd64.tar.gz"
    sha256 "4c5cd50ec8b5b81173433cb25707b3c2eeaf44aea72bb6667985cd88d8e10c2b"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/xsteadfastx/wg-quicker/releases/download/v0.5.2/wg-quicker_0.5.2_linux_armv6.tar.gz"
    sha256 "9872d8bf54dc25cd4b163da9b3f353ba8699b24773042b3ce802d2443e2da308"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/xsteadfastx/wg-quicker/releases/download/v0.5.2/wg-quicker_0.5.2_linux_arm64.tar.gz"
    sha256 "10d8bf316c76da474099763e6e9f58a571aca87ea1a0edf111790c2cdd5d9092"
  end

  def install
    bin.install "wg-quicker"
  end

  test do
    system "#{bin}/wg-quicker version"
  end
end
